# Generated by Django 5.2.8 on 2025-11-28 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0006_conversationsession_scenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('translation', models.TextField(blank=True, help_text="Translation in user's native language (optional)")),
                ('mastery_level', models.IntegerField(default=1, help_text='1: New, 2: Learning, 3: Reviewing, 4: Mastered, 5: Expert')),
                ('review_count', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_items', to='conversations.conversationsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vocabulary Item',
                'verbose_name_plural': 'Vocabulary Items',
                'db_table': 'vocabulary_items',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
