# Generated by Django 5.0.1 on 2025-11-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('icon', models.CharField(default='message-circle', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(default='blue', help_text='Color theme', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('conversation_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'topics',
                'ordering': ['difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('message_count', models.IntegerField(default=0)),
                ('user_message_count', models.IntegerField(default=0)),
                ('total_speaking_time', models.IntegerField(default=0, help_text='User speaking time in seconds')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='conversations.topic')),
            ],
            options={
                'verbose_name': 'Conversation Session',
                'verbose_name_plural': 'Conversation Sessions',
                'db_table': 'conversation_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('text', models.TextField(help_text='Message text (transcript for user, response for AI)')),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for user messages', null=True, upload_to='conversations/audio/')),
                ('duration', models.IntegerField(default=0, help_text='Audio duration in seconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.conversationsession')),
            ],
            options={
                'verbose_name': 'Conversation Message',
                'verbose_name_plural': 'Conversation Messages',
                'db_table': 'conversation_messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0, help_text='Overall score out of 100')),
                ('clarity_score', models.FloatField(default=0.0, help_text='Pronunciation and clarity')),
                ('fluency_score', models.FloatField(default=0.0, help_text='Speaking fluency and pace')),
                ('vocabulary_score', models.FloatField(default=0.0, help_text='Vocabulary richness')),
                ('grammar_score', models.FloatField(default=0.0, help_text='Grammar accuracy')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Speaking confidence')),
                ('engagement_score', models.FloatField(default=0.0, help_text='Conversation engagement')),
                ('feedback_text', models.TextField(blank=True, help_text='Detailed feedback')),
                ('strengths', models.TextField(blank=True, help_text='What the user did well')),
                ('improvements', models.TextField(blank=True, help_text='Areas for improvement')),
                ('tips', models.TextField(blank=True, help_text='Actionable tips')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='conversations.conversationsession')),
            ],
            options={
                'verbose_name': 'Conversation Feedback',
                'verbose_name_plural': 'Conversation Feedbacks',
                'db_table': 'conversation_feedbacks',
            },
        ),
    ]
