# Generated by Django 5.1.3 on 2025-11-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_documentupload_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='active', max_length=20),
        ),
    ]
