# Generated by Django 5.1.3 on 2025-11-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_alter_conversationsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='voice_preference',
            field=models.CharField(blank=True, choices=[('light_cheerful', 'Light & Cheerful'), ('warm_friendly', 'Warm & Friendly'), ('professional', 'Professional'), ('calm_soothing', 'Calm & Soothing')], help_text='Voice preference for this session (overrides user profile default)', max_length=20, null=True),
        ),
    ]
