# Generated by Django 5.2.8 on 2025-11-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_add_voice_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationfeedback',
            name='filler_word_count',
            field=models.IntegerField(default=0, help_text='Total filler words used'),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='filler_word_rate',
            field=models.FloatField(default=0.0, help_text='Filler words per minute'),
        ),
        migrations.AddField(
            model_name='conversationfeedback',
            name='filler_words_breakdown',
            field=models.JSONField(default=dict, help_text='Count by filler word type'),
        ),
    ]
