# Generated by Django 5.2.8 on 2025-11-28 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_add_filler_words'),
        ('training', '0002_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='training.scenario'),
        ),
    ]
