# Generated by Django 5.0.1 on 2025-12-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_conversationsession_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='conversation_depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='conversation_memory',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='conversationsession',
            name='emotion_trend',
            field=models.JSONField(default=list),
        ),
    ]
