# Generated by Django 5.2.8 on 2025-11-28 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('system_prompt', models.TextField(help_text='The roleplay instructions for the AI')),
                ('initial_message', models.TextField(help_text='The first message the AI sends')),
                ('objectives', models.JSONField(default=list, help_text='List of objectives for the user to complete')),
                ('icon', models.CharField(default='🎭', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'db_table': 'scenarios',
                'ordering': ['difficulty', 'title'],
            },
        ),
    ]
