# Generated by Django 5.1.3 on 2025-11-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerprofile',
            name='preferred_voice',
            field=models.CharField(choices=[('light_cheerful', 'Light & Cheerful'), ('warm_friendly', 'Warm & Friendly'), ('professional', 'Professional'), ('calm_soothing', 'Calm & Soothing')], default='warm_friendly', help_text='Preferred AI voice for conversations', max_length=20),
        ),
    ]
