# Generated by Django 5.1.3 on 2025-11-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_populate_default_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_applicant',
            field=models.BooleanField(default=True, help_text='Designates whether this user is an applicant.'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_hr',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as HR.'),
        ),
    ]
