# Generated by Django 5.1.3 on 2025-11-26 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_is_applicant_customuser_is_hr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_hr',
        ),
    ]
