# Generated by Django 5.1.3 on 2025-11-27 00:01

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_is_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRUser',
            fields=[
            ],
            options={
                'verbose_name': 'HR User',
                'verbose_name_plural': 'HR Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
