# Generated by Django 5.2.8 on 2025-11-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HRUser',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_applicant',
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='daily_goal_conversations',
            field=models.IntegerField(default=1, help_text='Daily conversation count goal'),
        ),
        migrations.AddField(
            model_name='learnerprofile',
            name='daily_goal_minutes',
            field=models.IntegerField(default=10, help_text='Daily speaking time goal in minutes'),
        ),
    ]
