# Generated by Django 5.2.8 on 2025-11-30 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0006_conversationsession_scenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_sessions', to='conversations.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'classroom_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('text', models.TextField()),
                ('correction', models.TextField(blank=True, help_text="Correction for user's mistake if any")),
                ('explanation', models.TextField(blank=True, help_text='Explanation of the correction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='classroom.classroomsession')),
            ],
            options={
                'db_table': 'classroom_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
